// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Services.Database;

#nullable disable

namespace eCommerce.Services.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260706223543_CineVisionUpdates")]
    partial class CineVisionUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eCommerce.Services.Database.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-energy action films",
                            IsActive = true,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Character-driven dramatic stories",
                            IsActive = true,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light-hearted and funny films",
                            IsActive = true,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Science fiction and futuristic stories",
                            IsActive = true,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suspense and horror films",
                            IsActive = true,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ScreenType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Main auditorium with 40 seats",
                            IsActive = true,
                            Name = "Hall A",
                            ScreenType = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smaller auditorium with 24 seats",
                            IsActive = true,
                            Name = "Hall B",
                            ScreenType = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MovieState")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PosterImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = "PG-13",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A soldier relives the same brutal battle in a loop against an alien invasion.",
                            Director = "Doug Liman",
                            DurationMinutes = 113,
                            GenreId = 4,
                            IsActive = true,
                            Language = "English",
                            MovieState = "ActiveMovieState",
                            ReleaseDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Edge of Tomorrow",
                            ViewCount = 320
                        },
                        new
                        {
                            Id = 2,
                            AgeRating = "PG",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An ageing comedian gets one final shot at the spotlight.",
                            Director = "Greta Park",
                            DurationMinutes = 98,
                            GenreId = 3,
                            IsActive = true,
                            Language = "English",
                            MovieState = "ActiveMovieState",
                            ReleaseDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Last Laugh",
                            ViewCount = 140
                        },
                        new
                        {
                            Id = 3,
                            AgeRating = "R",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A family moves into a house that hides a terrifying secret.",
                            Director = "Mark Reyes",
                            DurationMinutes = 105,
                            GenreId = 5,
                            IsActive = true,
                            Language = "English",
                            MovieState = "ActiveMovieState",
                            ReleaseDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Silent Shadows",
                            ViewCount = 210
                        },
                        new
                        {
                            Id = 4,
                            AgeRating = "PG-13",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two strangers cross the country and find unexpected friendship.",
                            Director = "Lena Holt",
                            DurationMinutes = 127,
                            GenreId = 2,
                            IsActive = true,
                            Language = "English",
                            MovieState = "ActiveMovieState",
                            ReleaseDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Broken Roads",
                            ViewCount = 90
                        },
                        new
                        {
                            Id = 5,
                            AgeRating = "PG-13",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An elite agent races to stop a global catastrophe.",
                            Director = "Sam Okafor",
                            DurationMinutes = 118,
                            GenreId = 1,
                            IsActive = true,
                            Language = "English",
                            MovieState = "ActiveMovieState",
                            ReleaseDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Final Strike",
                            ViewCount = 260
                        },
                        new
                        {
                            Id = 6,
                            AgeRating = "PG-13",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A physicist discovers a way to travel between parallel worlds.",
                            Director = "Iris Vance",
                            DurationMinutes = 134,
                            GenreId = 4,
                            IsActive = true,
                            Language = "English",
                            MovieState = "DraftMovieState",
                            ReleaseDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Quantum Drift",
                            ViewCount = 60
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReservationNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("eCommerce.Services.Database.ReservationSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.HasIndex("ScreeningId", "SeatId")
                        .IsUnique();

                    b.ToTable("ReservationSeats");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Loved the relentless time-loop action.",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            Rating = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Comment = "A great sci-fi thrill ride.",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 1,
                            Rating = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Solid, fast-paced action.",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 5,
                            Rating = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "A charming but slight comedy.",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 2,
                            Rating = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Creepy atmosphere, slow middle.",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 3,
                            Rating = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Comment = "A heartfelt cross-country journey.",
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MovieId = 4,
                            Rating = 5,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role with full permissions",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default customer role",
                            IsActive = true,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Employee role for content management and analytics",
                            IsActive = true,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 8.50m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 7, 5, 19, 53, 0, 0, DateTimeKind.Utc),
                            HallId = 1,
                            HasSubtitles = false,
                            IsActive = true,
                            Language = "English",
                            MovieId = 1,
                            StartTime = new DateTime(2026, 7, 5, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 8.50m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 7, 5, 22, 53, 0, 0, DateTimeKind.Utc),
                            HallId = 1,
                            HasSubtitles = true,
                            IsActive = true,
                            Language = "English",
                            MovieId = 1,
                            StartTime = new DateTime(2026, 7, 5, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 7.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 7, 6, 19, 8, 0, 0, DateTimeKind.Utc),
                            HallId = 1,
                            HasSubtitles = false,
                            IsActive = true,
                            Language = "English",
                            MovieId = 2,
                            StartTime = new DateTime(2026, 7, 6, 17, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 9.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 7, 6, 21, 45, 0, 0, DateTimeKind.Utc),
                            HallId = 2,
                            HasSubtitles = false,
                            IsActive = true,
                            Language = "English",
                            MovieId = 3,
                            StartTime = new DateTime(2026, 7, 6, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 10.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new DateTime(2026, 7, 7, 20, 58, 0, 0, DateTimeKind.Utc),
                            HallId = 2,
                            HasSubtitles = true,
                            IsActive = true,
                            Language = "English",
                            MovieId = 5,
                            StartTime = new DateTime(2026, 7, 7, 19, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "RowLabel", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 2,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 3,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 4,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 5,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 6,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 7,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 7,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 8,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 8,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 9,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 10,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 11,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 12,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 13,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 14,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 15,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 7,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 16,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 8,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 17,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 18,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 19,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 20,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 21,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 22,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 23,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 7,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 24,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 8,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 25,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 26,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 27,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 28,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 29,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 30,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 31,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 7,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 32,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 8,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 33,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 1,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 34,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 2,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 35,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 3,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 36,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 4,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 37,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 5,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 38,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 6,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 39,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 7,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 40,
                            HallId = 1,
                            IsActive = true,
                            RowLabel = "E",
                            SeatNumber = 8,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 41,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 42,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 43,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 44,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 45,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 46,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "A",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 47,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 48,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 49,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 50,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 51,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 52,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "B",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 53,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 1,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 54,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 2,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 55,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 3,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 56,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 4,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 57,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 5,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 58,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "C",
                            SeatNumber = 6,
                            SeatType = 0
                        },
                        new
                        {
                            Id = 59,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 1,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 60,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 2,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 61,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 3,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 62,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 4,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 63,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 5,
                            SeatType = 1
                        },
                        new
                        {
                            Id = 64,
                            HallId = 2,
                            IsActive = true,
                            RowLabel = "D",
                            SeatNumber = 6,
                            SeatType = 1
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@gmail.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "5kRBQg4Ufcx4hAknG7P9zhfLPvY=",
                            PasswordSalt = "FmvmUwPsJyRRffhNRQvbrA==",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@gmail.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Staff",
                            PasswordHash = "GBoyh1WP+OMgGjqRj6vK6L1+oGc=",
                            PasswordSalt = "0AXpKx6xRp9xM42jCf/PiA==",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin3@gmail.com",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Staff",
                            PasswordHash = "x6JHKCTQywdAzTcZxGWFvrKPORM=",
                            PasswordSalt = "IwhTfKQNgyqWfOlTqCDXrg==",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@gmail.com",
                            FirstName = "Dave",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "E0fA2/f9GZvIRRt/cgqQemG/Cog=",
                            PasswordSalt = "TiJxWTJcd7sBSiWNbhK9Vw==",
                            Username = "customer1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@gmail.com",
                            FirstName = "Eve",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "Ov4LxpWKXXV9dwMYvBgqODdzIt0=",
                            PasswordSalt = "KtWF6g7SemBqs4nVWV4Ziw==",
                            Username = "customer2"
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("eCommerce.Services.Database.Asset", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Movie", "Movie")
                        .WithMany("Assets")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Movie", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("eCommerce.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Reservation", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Screening", "Screening")
                        .WithMany("Reservations")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Screening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.ReservationSeat", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Reservation", "Reservation")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.Screening", "Screening")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.Seat", "Seat")
                        .WithMany("ReservationSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Screening");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Review", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Screening", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Hall", "Hall")
                        .WithMany("Screenings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Seat", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("eCommerce.Services.Database.UserRole", b =>
                {
                    b.HasOne("eCommerce.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Hall", b =>
                {
                    b.Navigation("Screenings");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Movie", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Reviews");

                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Reservation", b =>
                {
                    b.Navigation("ReservationSeats");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Screening", b =>
                {
                    b.Navigation("ReservationSeats");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("eCommerce.Services.Database.Seat", b =>
                {
                    b.Navigation("ReservationSeats");
                });

            modelBuilder.Entity("eCommerce.Services.Database.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
