@CineVision.WebAPI_HostAddress = http://localhost:5126

### Login
POST {{CineVision.WebAPI_HostAddress}}/Access/Login
Content-Type: application/json

{
  "username": "admin1",
  "password": "Test123"
}
